### ISSUE TITLE
Consider renaming repo to paired

### ISSUE THREAD

**Issue by webmaster128** [filecoin-project/pairing#18]
As this repo is pubushed as the paired crate, I think it would be very helpful to rename the repo to paired as well. This reduces confusion for newcomes like me and makes navigation on Github faster.

**Comment by dignifiedquire** [comment]
Unfortunately we can't, as github doesn't allow us to rename forks :/

**Comment by algarecu** [comment]
I was also confused by the fact that this is the same than the Rust lib, https://docs.rs/crate/paired/0.19.1, isn't it? Noticed that the filecoin-project/pairing is actually packaged as `[package]
name = "paired"`. I would suggest to document this explicitly if not done yet to avoid confusion as it seems that repo can't be renamed.

**Comment by webmaster128** [comment]
Hmm, I wonder what the problem is really. I was able to rename my fork to https://github.com/webmaster128/paired

**Comment by algarecu** [comment]
> Unfortunately we can't, as github doesn't allow us to rename forks :/

I was also confused by the fact that this is the same than the Rust lib, https://docs.rs/crate/paired/0.19.1, isn't it? Noticed that the filecoin-project/pairing is actually packaged as [package] name = "paired". I would suggest to document this explicitly if not done yet to avoid confusion as it seems that repo can't be renamed.

**Comment by algarecu** [comment]
> Hmm, I wonder what the problem is really. I was able to rename my fork to https://github.com/webmaster128/paired

Yeah, probably if you have github pro you can and still, should be alright. I have renamed repos before.

**Comment by webmaster128** [comment]
>  if you have github pro

I don't have Pro.

The reason might be that other repos forked this one. But that's just a wild guess.

**Comment by dignifiedquire** [comment]
I believe this is a new functionality, I was able to rename it now, but wasn't the last time I tried Oo

**Comment by webmaster128** [comment]
Amazing, thank you @dignifiedquire. Seems like a tiny change but this really helps people trying to navigate the ecosystem.
